on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  #push:
   #branches:
     #- master
 # pull_request:
   #   types: [opened, synchronize, reopened]
  #workflow_call:
  #  inputs:
  #    organization:
  #      required: true
  #      type: string
   #   project_Key:
  #      required: true
  #      type: string
  #  secrets:
  #    sonar_token: 
   #     required: false
  workflow_dispatch:
    inputs:
      organization:
        required: true
      project_key:
        required: true
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=${{ inputs.organization }}
          -Dsonar.projectKey=${{ inputs.project_key }}
          -Dsonar.sources=.   
          -Dsonar.host.url=https://sonarcloud.io

      
